# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.16.2'
  displayName: 'Install Node.js'
- script: |
    nvm use 12.16.2
  displayName: 'nvm use version'
- task: CopyFilesOverSSHUp@0
  inputs:
    sshEndpoint: 'centos test'
    contents: '**/*.md'
    targetFolder: '/writable'
    readyTimeout: '20000'
    failOnEmptySource: true

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'
