jobs:
  - job: 'VS2017_Win2016'
    pool: 'Hosted VS2017'
    steps:
      - task: JavaToolInstallerPatch0620@0
        displayName: 'Use Java 1.7'
        inputs:
          versionSpec: 7
          jdkArchitectureOption: x64
          jdkSourceOption: AzureStorage
          azureResourceManagerEndpoint: 'XPLATALM-DevManaged (f233b65d-2603-40d9-8486-18f49ca15e4e)'
          azureStorageAccountName: kejstorage
          azureContainerName: 'java-jdk-test-container'
          azureCommonVirtualFile: 'zulu-7-azure-jdk_7.24.0.2-7.0.191-win_x64.zip'
          jdkDestinationDirectory: /tempAzure

      - task: Maven@1
        displayName: 'Maven JavaTestProject/pom.xml'
        inputs:
          mavenPomFile: '$(build.sourcesdirectory)/src/javaToolInstaller/JavaTestProject/pom.xml'
          javaHomeOption: Path
          jdkDirectory: '$(JAVA_HOME)'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(build.sourcesdirectory)/src/javaToolInstaller/'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'