jobs:
  - job: 'VS2017_Win2016'
    pool: 'Hosted VS2017'
    steps:
      - task: JavaToolInstallerPatch0620@0
        displayName: 'Unpack Java, inactive Cleaning'
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x86'
          jdkSourceOption: 'PreInstalled'
      - task: Maven@3
        displayName: 'Maven JavaTestProject/pom.xml'
        inputs:
          mavenPomFile: '$(build.sourcesdirectory)/JavaTestProject/pom.xml'
          javaHomeOption: Path
          jdkDirectory: '$(JAVA_HOME)'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(build.sourcesdirectory)'
          Contents: '**/*.jar'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        inputs:
          PathtoPublish: '$(build.artifactstagingdirectory)'
